import { Injectable } from '@angular/core';
import { Article } from '../interfaces/article';
import { Observable, of } from 'rxjs';
import { catchError, tap } from 'rxjs/operators';

import { HttpClient, HttpHeaders } from '@angular/common/http';
import { LoginService } from '../services/login.service';

@Injectable({
  providedIn: 'root'
})
export class NewsService {

  private newsUrl = 'http://sanger.dia.fi.upm.es/pui-rest-news/articles';  // URL to web api
  private articleUrl = 'http://sanger.dia.fi.upm.es/pui-rest-news/article';  // URL to web api

  constructor(private http: HttpClient) {
    this.APIKEY = null;
    // Initialize with anonymous API key
    this.setAnonymousApiKey();
  }

  // Set the corresponding APIKEY accordig to the received by email
  private APIKEY: string | null;
  private APIKEY_ANON = 'ANON02'; // Replace with your group's anonymous API key

  private httpOptions = {
    headers: new HttpHeaders({
      'Content-Type': 'application/json',
      Authorization: 'PUIRESTAUTH apikey=' + this.APIKEY_ANON
    })
  };

  // Modifies the APIKEY with the received value
  setUserApiKey(apikey: string | undefined) {
    if (apikey) {
      this.APIKEY = apikey;
    }
    this.httpOptions = {
      headers: new HttpHeaders({
        'Content-Type': 'application/json',
        Authorization: 'PUIRESTAUTH apikey=' + this.APIKEY
      })
    };
  }

  setAnonymousApiKey() {
    this.setUserApiKey(this.APIKEY_ANON);
  }

  // Returns the list of news contain elements with the following fields:
  // {"id":...,
  //  "id_user":...,
  //  "abstract":...,
  //  "subtitle":...,
  //  "update_date":...,
  //  "category":...,
  //  "title":...,
  //  "thumbnail_image":...,
  //  "thumbnail_media_type":...}

  getArticles(): Observable<Article[]> {
    return this.http.get<Article[]>(this.newsUrl, this.httpOptions).pipe(
      tap(response => {
        // Articles loaded successfully
      }),
      catchError(error => {
        console.error('Error loading articles:', error);
        return of([]); // Return empty array on error
      })
    );
  }

  deleteArticle(article: Article | number | string): Observable<Article> {
    let id: string | number;
    
    if (typeof article === 'object' && article !== null) {
      id = article.id;
    } else {
      id = article;
    }
    
    const url = `${this.articleUrl}/${id}`;
    
    return this.http.delete<Article>(url, this.httpOptions).pipe(
      catchError(error => {
        console.error('Delete failed:', error);
        throw error;
      })
    );
  }


  // Returns an article which contains the following elements:
  // {"id":...,
  //  "id_user":...,
  //  "abstract":...,
  //  "subtitle":...,
  //  "update_date":...,
  //  "category":...,
  //  "title":...,
  //  "image_data":...,
  //  "image_media_type":...}


  getArticle(id: string|null): Observable<Article> {
    const url = `${this.articleUrl}/${id}`;
    return this.http.get<Article>(url, this.httpOptions);

  }

  updateArticle(article: Article): Observable<Article> {
    return this.http.post<Article>(this.articleUrl, article, this.httpOptions);
  }

    createArticle(article: Article): Observable<Article> {
    // For creation, remove the ID field as it should be generated by the server
    const { id, ...articleForCreation } = article;
    
    return this.http.post<Article>(this.articleUrl, articleForCreation, this.httpOptions).pipe(
      catchError(error => {
        console.error('Create article failed:', {
          status: error.status,
          statusText: error.statusText,
          url: error.url,
          message: error.message,
          body: error.error,
          requestData: articleForCreation
        });
        throw error;
      })
    );
  }
}
